### PR TITLE
Add assetsExt rpc definitions

### PR DESCRIPTION
**Pull request by KarishmaBothara**
## Summary

Add free balance rpc definition for assetsExt
## Checklist

- [x] Add description

### CODE REVIEW

**Review by ken-centrality — COMMENTED** [review]
Can you please
- re-generate runtimes for 5.48.9
- add RPC info for `sft_tokenUri`
- fix the lint issue

**Comment by ken-centrality** [comment]
make a commit to help with the `prettier` issue @KarishmaBothara, but there are some failed tests

**Comment by KarishmaBothara** [comment]
> make a commit to help with the `prettier` issue @KarishmaBothara, but there are some failed tests

I will check

**Review by ken-centrality — APPROVED** [review]
LGTM

**Pull request merged**
